### ISSUE TITLE
Generalize one-line installer

### ISSUE THREAD

**Issue by 5chdn** [paritytech/scripts#31]
AFTER: https://github.com/paritytech/parity/pull/8887

We have to rethink the one-line installer logic after we remove debian/centos pipelines.

Now, that `libssl` is not an issue anymore, I would suggest just looking:

```
IF system IS windows THEN
    GET parity.exe FROM windows
ELSIF system IS macos THEN
    GET parity FROM macos
ELSIF system IS linux THEN
    CHECK architecture 
    GET parity FROM linux AND architecture
```

I know you want to take this @fevo1971 :D

**Comment by 5chdn** [comment]
This is actually independent from the PR linked above because the binaries are already existing.

**Comment by ddorgan** [comment]
@5chdn will do!

**Comment by fevo1971** [comment]
i just merged the new version of the installer script. because we no longer supply
distribution/os specific packages it installs only the parity-binary.

note:
if parity releases where maintained via a package-manager (like rpm, dpkg or pkg on mac)
in the past, it's a good idea to uninstall the parity package manualy before executing
*get-parity.sh*.

**Comment by 5chdn** [comment]
I'll add this to the release notes. Thanks!
